version: "3.9"
services:
  app:
    image: "weather:latest"
    build:
      context: .
    ports:
      - "9595-9597:8080"
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - weather-networks
    environment:
      - "API_KEY=${API_KEY}"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - weather-networks
  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - weather-networks
networks:
  weather-networks: